name: Cypress Tests
on:
  workflow_dispatch:
    inputs:
      spec:
          description: Run by cypress command line
          default: api/cypress/e2e/*
jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-22.11.0-chrome-130.0.6723.116-1-ff-132.0.1-edge-130.0.2849.68-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: yarn install

      - name: Run E2E tests
        run: node ./cypress-automacao-teste/api/runner-electron.js
    env:
      TARGET_TOKEN_ELECTRON: ${{ secrets.TARGET_TOKEN_ELECTRON_API }}
    
